export const LOGIN = 'employee/login';
export const DSR = 'job/dsr/get';
export const DSR_FILTER = 'job/filters/dsr';
export const DSR_SHARE = 'job/get/dsr/'
export const DSR_DELETE = 'job/dsr/';
export const EMPLOYEE_PROFILE = 'employee';
export const ALL_EMPLOYEE = 'employee/photos';
export const GET_TASK = 'task/get';
export const TASK_SHARE = 'task/';
export const GET_CLIENTS = 'clients';
export const REFERENCE = 'clients/reference';
export const SEARCH_CLIENT = 'search/clients'
export const CREATE_TASK = 'task';
export const GET_ATTENDANCE = 'leave';
export const GET_TRACKING = 'track';
export const CALENDAR = 'calendar';
export const TEAM = 'team';
export const TEAM_CHART = 'team/chart/';
export const CHART = 'chart';
export const DOWNLOAD = 'download';
export const LEAD = 'lead/status';
export const LEAD_DATA = 'lead/data';
export const NOTIFICATION = 'notification';
export const CLOUDINARY = 'cloudinary';
export const CHART_TYPE_DATA = 'chart/general';
export const CHART_TABLE_DATA = 'chart/table';
export const CHART_DOWNLOAD_DATA = 'chart/download'

export const COLORS = ["#ff6283", "#36a1eb", "#5cc6c6", "#ffcd56", "#a071ff"];

export const CLOUDINARY_NAME = "hlmzh75cl";
export const CLOUDINARY_PRESET = "ij5cs5za";
